apiVersion: batch/v1
kind: CronJob
metadata:
  name: chatsummarizer
spec:
  schedule: "0 19 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/app: chatsummarizer
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: shared
              persistentVolumeClaim:
                claimName: ollama
          containers:
            - name: ollama
              image: ghcr.io/diverofdark/telegramsummarizer:master
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /ollama/
                  name: shared
              env:
                - name: OLLAMA_URL
                  value: http://ollama
                - name: USER_DATADIR
                  value: /ollama/userbot
                - name: OLLAMA_PATH
                  value: /ollama
              envFrom:
                - secretRef:
                    name: chatsummarizer-secret
                    optional: true