apiVersion: batch/v1
kind: CronJob
metadata:
  name: chatsummarizer
spec:
  schedule: "0 19 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/app: chatsummarizer
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: shared
              persistentVolumeClaim:
                claimName: ollama
          containers:
            - name: ollama
              image: ghcr.io/diverofdark/telegramsummarizer:master
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /models/
                  name: shared
              securityContext:
                runAsUser: 0
                runAsGroup: 0
              resources:
                requests:
                  memory: "128Mi"
                limits:
                  memory: "1Gi"
              env:
                - name: USER_SEND
                  value: "true"
                - name: OLLAMA_URL
                  value: http://ollama
                - name: USER_DATADIR
                  value: /models/userbot
                - name: OLLAMA_PATH
                  value: /models/
              envFrom:
                - secretRef:
                    name: chatsummarizer-secret
                    optional: true