apiVersion: batch/v1
kind: CronJob
metadata:
  name: chatsummarizer
spec:
  schedule: "0 19 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/app: chatsummarizer
        spec:
          volumes:
            - name: shared
              persistentVolumeClaim:
                claimName: ollama
          containers:
            - name: ollama
              image: ollama/ollama:latest
              volumeMounts:
                - mountPath: /ollama/
                  name: shared
              envFrom:
                - secretRef:
                    name: chatsummarizer-secret
                    optional: true