apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/app: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/app: ollama
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - asgard
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: ollama
        - name: localdata
          emptyDir: {}
      containers:
        - name: ollama
          image: ollama/ollama:latest
          volumeMounts:
            - mountPath: /root/.ollama
              name: localdata
            - mountPath: /models
              name: models
          resources:
            requests:
              memory: "12Gi"
            limits:
              memory: "12Gi"
          ports:
            - name: http
              protocol: TCP
              containerPort: 11434
          livenessProbe:
            httpGet:
              path: /api/tags
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/tags
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
