apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---