apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 11434
  selector:
    app.kubernetes.io/app: ollama
  type: ClusterIP
---